### ISSUE TITLE
$signOut() doesn't return promise in the latest release

### ISSUE THREAD

**Issue by SamarRizvi** [firebase/angularfire#835]
Hi, $signOut() doesn't return promise in the release 2.0.1

**Comment by jwngr** [comment]
Dupe of #755. This is fixed with #771 but just hasn't been released yet.

Also, please use the issue template in the future.

**Comment by jwngr** [comment]
This is fixed in the just-released AngularFire [version 2.0.2](https://github.com/firebase/angularfire/releases/tag/v2.0.2). Sorry for the delay in getting it out!

**Comment by SamarRizvi** [comment]
Thanks @jwngr

**Comment by bpkennedy** [comment]
```
angular.module('shockballApp')
  .factory('Auth', function ($firebaseAuth) {
      return $firebaseAuth();
  });

angular.module('shockballApp')
.controller('LoginCtrl', function ($state, Auth) {
    var login = this;
    login.auth = Auth;
    login.signOut = function() {
        login.auth.$signOut().then(function(response) {
            console.log(response);
            console.log('signed out with ' + response);
        });
    };
});
```

The response from `login.auth.$signOut()` is still returning null/undefined for me.  I double checked my bower_components angularfire.js and it is  * AngularFire 2.0.2, so I am assuming this is still an issue?

**Comment by jwngr** [comment]
As your code shows, `$signOut()` is returning a promise or else your `then()` block would not fire. The promise returned from that method is intended to be empty, meaning `response` will be `undefined`. This is expected behavior. I just updated the [`$signOut()` API reference docs](https://github.com/firebase/angularfire/blob/master/docs/reference.md#signout) to make this more obvious.
